import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path'; import {tmpdir} from 'node:os'; import {randomUUID} from 'node:crypto'; import assert from 'node:assert/strict';
import {connectPeer} from './pipe-client.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms)); const root=resolve(new URL('..',import.meta.url).pathname.slice(1)); const exe=join(root,'runtime/target/debug/threadterm-v3-runtime.exe');
const scratch=await mkdtemp(join(tmpdir(),'threadterm-v3-relocation-')); const source=join(scratch,'source'),target=join(scratch,'target'),project=join(scratch,'project'); await Promise.all([mkdir(source),mkdir(target),mkdir(project)]); const pipe=`\\\\.\\pipe\\threadterm-v3-relocation-${randomUUID()}`; let daemon,peer;
async function start(data){ daemon=spawn(exe,[],{windowsHide:true,env:{...process.env,THREADTERM_V3_DATA:data,THREADTERM_V3_PIPE:pipe},stdio:'ignore'}); for(let n=0;n<100;n++){try{const p=await connectPeer(`${pipe}-control`);await p.auth((await readFile(join(data,'runtime.credential'),'utf8')).trim());return p}catch{await delay(50)}}throw Error('runtime startup timeout') }
try { peer=await start(source); const projectRow=await peer.request('project.add',{path:project,operationId:randomUUID()}); const preparedOperationId=randomUUID(); const prepared=await peer.request('data.relocation.prepare',{targetPath:target,operationId:preparedOperationId}); assert.ok(prepared.targetRoot.endsWith(target)); await assert.rejects(peer.request('settings.update',{patch:{theme:'light'},expectedRevision:0,operationId:randomUUID()})); await peer.request('data.relocation.cancel',{preparedOperationId,operationId:randomUUID()}); assert.equal((await peer.request('data.relocation.status',{})).frozen,false); const replayed=await peer.request('data.relocation.prepare',{targetPath:target,operationId:preparedOperationId}); assert.equal(replayed.activationToken,prepared.activationToken); assert.equal((await peer.request('data.relocation.status',{})).frozen,true); await peer.request('runtime.shutdown',{operationId:randomUUID()}); peer.close(); await new Promise(r=>daemon.once('exit',r)); assert.ok((await readFile(join(target,'runtime.credential'),'utf8')).trim()); peer=await start(target); const restored=await peer.request('runtime.snapshot',{}); assert.ok(restored.projects.some(row=>row.id===projectRow.id)); await peer.request('runtime.shutdown',{operationId:randomUUID()}); peer.close(); await new Promise(r=>daemon.once('exit',r)); console.log(JSON.stringify({passed:true,checks:['empty target','freeze mutations','separate cancel operation','prepare replay re-freezes','SQLite backup','credential copy','source preserved','new runtime snapshot']})); }
finally { peer?.close(); if(daemon?.exitCode===null)daemon.kill(); for(let attempt=0;attempt<10;attempt+=1){try{await rm(scratch,{recursive:true,force:true});break}catch(error){if(attempt===9)throw error;await delay(100)}} }


