import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import type { Session, Snapshot, UsageRecord, UsageResult, Worktree } from '@threadterm/protocol';
import { operationId, request } from '../bridge';
import { isActionableInboxItem } from '../inboxVisibility';
import { displayPath, sameCanonicalScope } from '../projectScope';
import { useTranslation } from '../i18n';
import { AgentIcon, Icon } from './PrototypeIcon';
import { FileWorkspace } from './FileWorkspace';
import { UsagePanel } from './UsagePanel';
import { SurfaceDialog } from './SurfaceDialog';
import { WorktreeManager } from './WorktreeManager';
import './project-overview.css';
import { sessionTime } from '../sessionTime';
import { sessionState, sessionStateLabel, type SessionViewState } from '../sessionState';

type Props={projectId:string;data:Snapshot;initialWorktreePath?:string;onScopeChange:(path?:string)=>void;onSession:(id:string)=>void;onRemoved:()=>void;onCreate:(projectId:string,path:string)=>void;onInbox:()=>void;onChanged:()=>void};
type ViewState=SessionViewState;
const stateOf=sessionState,badgeText=(value:ViewState,zh:boolean)=>sessionStateLabel(value,zh);
const providerName=(id:string)=>id==='claude'?'Claude':id==='opencode'?'OpenCode':id[0].toUpperCase()+id.slice(1);
function priority(list:Session[]):ViewState{return (['needs','failed','running','stalled','ended'] as const).find(state=>list.some(item=>stateOf(item)===state))??'ended';}
function Spark({values,fill=false}:{values:number[];fill?:boolean}){const max=Math.max(1,...values),width=180,height=20;const points=values.map((value,index)=>`${index*width/Math.max(1,values.length-1)},${height-2-value/max*(height-4)}`).join(' ');return <svg className="spark" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true">{fill&&<polygon points={`0,${height} ${points} ${width},${height}`} fill="currentColor" opacity=".16"/>}<polyline points={points} stroke="currentColor" strokeWidth="1.7" fill="none" vectorEffect="non-scaling-stroke"/>{values.length>0&&<circle cx={width} cy={height-2-values.at(-1)!/max*(height-4)} r="1.8" fill="currentColor"/>}</svg>;}

export function ProjectOverview({projectId,data,initialWorktreePath,onScopeChange,onSession,onRemoved,onCreate,onInbox,onChanged}:Props){
  const {locale,formatDate}=useTranslation(),zh=locale==='zh-CN',project=data.projects.find(p=>p.id===projectId)!;
  const [trees,setTrees]=useState<Worktree[]>([]),[usage,setUsage]=useState<UsageResult>(),[issue,setIssue]=useState<string>(),[dialog,setDialog]=useState<'usage'|'follow'|'activity'|'tree'|'manage'|undefined>(),[fileView,setFileView]=useState<'file'|'diff'|undefined>();
  const [followQuery,setFollowQuery]=useState(''),[picked,setPicked]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[activityPage,setActivityPage]=useState(0);
  useEffect(()=>{let current=true;setIssue(undefined);void request('worktree.list',{projectId}).then(value=>{if(current)setTrees(value);}).catch(error=>{if(current)setIssue(String(error));});void request('usage.query',{projectId}).then(value=>{if(current)setUsage(value);}).catch(()=>{if(current)setUsage(undefined);});return()=>{current=false;};},[projectId,data.revision]);
  const tree=trees.find(t=>sameCanonicalScope(t.path,initialWorktreePath));
  const sessions=data.sessions.filter(s=>s.projectId===projectId&&!s.archived&&(!initialWorktreePath||sameCanonicalScope(s.worktreePath??project.path,initialWorktreePath)));
  const allProjectSessions=data.sessions.filter(s=>s.projectId===projectId&&!s.archived);
  const followed=sessions.filter(s=>s.followed), ids=new Set(sessions.map(s=>s.id));
  const attention=data.inbox.filter(i=>isActionableInboxItem(i)&&ids.has(i.sessionId));
  const state=tree?.missing?'stalled':priority(sessions),path=initialWorktreePath??project.path;
  const treeFor=(s:Session)=>trees.find(t=>sameCanonicalScope(t.path,s.worktreePath??project.path));
  const time=(value:string)=>sessionTime(value,locale);
  const records=(usage?.records??[]).filter(row=>ids.has(row.sessionId)),today=new Date();today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()-6);
  const period=(from:Date)=>records.filter(r=>new Date(r.recordedAt)>=from);
  const todayRows=period(today),weekRows=period(week);
  const tokens=(rows:UsageRecord[])=>{const known=rows.filter(r=>r.inputTokens!==undefined||r.outputTokens!==undefined);return known.length?known.reduce((sum,r)=>sum+(r.inputTokens??0)+(r.outputTokens??0),0):undefined;};
  const number=(value:number|undefined)=>value===undefined?'—':new Intl.NumberFormat(locale,{notation:'compact',maximumFractionDigits:2}).format(value);
  const cost=(rows:UsageRecord[])=>{const known=rows.filter(r=>r.estimatedCost!==undefined&&r.currency);const currency=known[0]?.currency;if(!known.length||known.some(r=>r.currency!==currency))return zh?'费用未知':'Cost unknown';return new Intl.NumberFormat(locale,{style:'currency',currency}).format(known.reduce((sum,r)=>sum+r.estimatedCost!,0));};
  const usageSeries=Array.from({length:7},(_,index)=>{const from=new Date(week);from.setDate(from.getDate()+index);const until=new Date(from);until.setDate(until.getDate()+1);return tokens(weekRows.filter(row=>new Date(row.recordedAt)>=from&&new Date(row.recordedAt)<until))??0;});
  const activeTrees=trees.filter(t=>allProjectSessions.some(s=>sameCanonicalScope(s.worktreePath??project.path,t.path)&&stateOf(s)!=='ended'));
  const activity=sessions.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const closed=()=>{if(!busy)setDialog(undefined);};
  const follow=async()=>{setBusy(true);setIssue(undefined);try{await Promise.all([...picked].map(sessionId=>request('session.update',{sessionId,followed:true,operationId:operationId()})));setDialog(undefined);onChanged();}catch(error){setIssue(String(error));}finally{setBusy(false);}};
  const remove=async()=>{if(!confirm(zh?`从 ThreadTerm 移除 ${project.name}？项目文件会保留。`:`Remove ${project.name} from ThreadTerm? Project files are kept.`))return;try{await request('project.remove',{id:projectId,operationId:operationId()});onRemoved();}catch(error){setIssue(String(error));}};
  const scopeBranch=Boolean(initialWorktreePath),live=(s:Session)=>stateOf(s)!=='ended';
  const rank:Record<ViewState,number>={needs:0,failed:1,running:2,stalled:3,ended:4};
  const activeSessions=sessions.filter(live).sort((a,b)=>rank[stateOf(a)]-rank[stateOf(b)]||b.updatedAt.localeCompare(a.updatedAt));
  // A branch page lists its live sessions above, so its timeline only adds the ended ones (no row twice).
  const recent=scopeBranch?activity.filter(s=>!live(s)):activity;
  const knownCost=(rows:UsageRecord[])=>{const text=cost(rows);return text===(zh?'费用未知':'Cost unknown')?undefined:text;};
  const todayTokens=tokens(todayRows),weekTokens=tokens(weekRows),usageLabel=scopeBranch?(zh?'本分支用量':'Branch usage'):(zh?'本项目用量':'Project usage');
  const metric=(label:string,value:number,cls?:ViewState,click?:()=>void)=>{const body=<><span className="ov-metric-label">{label}</span><b className={`tnum${cls&&value?' st-'+cls:''}`}>{value}</b></>;return click?<button type="button" className="ov-metric" onClick={click}>{body}</button>:<div className="ov-metric">{body}</div>;};
  const section=(key:string,title:string,count:number|undefined,action:ReactNode,body:ReactNode)=><section className={`ov-sec ov-sec-${key}`} data-testid={`home-${key}`}><header className="ov-sec-head"><h2>{title}{count!==undefined&&<span className="count">{count}</span>}</h2>{action}</header>{body}</section>;
  const empty=(text:string)=><p className="ov-empty">{text}</p>;
  const sessionRow=(s:Session,context:string)=><button type="button" key={s.id} className="ov-row" onClick={()=>onSession(s.id)}><AgentIcon provider={s.provider}/><span className="ov-row-main"><span className="ov-row-title">{s.title}</span><span className="ov-row-ctx">{context}</span></span><span className={`chip st-${stateOf(s)}`}>{badgeText(stateOf(s),zh)}</span><Icon name="chevR" className="ov-row-go"/></button>;
  const activityRows=(rows:Session[])=><div className="ov-list">{rows.map(s=><button type="button" key={s.id} className="ov-row ov-row-timed" onClick={()=>onSession(s.id)}><span className="ov-row-time" title={formatDate(s.updatedAt)}>{time(s.updatedAt)}</span><AgentIcon provider={s.provider}/><span className="ov-row-main"><span className="ov-row-title">{s.title}</span><span className="ov-row-ctx">{[badgeText(stateOf(s),zh),providerName(s.provider),...(scopeBranch?[]:[treeFor(s)?.branch??(zh?'项目目录':'Project directory')])].join(' · ')}</span></span><Icon name="chevR" className="ov-row-go"/></button>)}</div>;
  if(fileView)return <section className="project-file-page"><header className="ws-top"><button className="ws-back" onClick={()=>setFileView(undefined)}><Icon name="back"/>{project.name}</button><span className="ws-chip branch">{tree?.branch??trees.find(t=>t.isMain)?.branch??(zh?'项目目录':'Project directory')}</span><span className="ws-path" title={displayPath(path)}>{displayPath(path)}</span><span className="grow"/><button className="btn" onClick={()=>setFileView(fileView==='file'?'diff':'file')}>{fileView==='file'?(zh?'查看更改':'Changes'):(zh?'文件':'Files')}</button></header><FileWorkspace projectId={projectId} worktreePath={initialWorktreePath} initialView={fileView} rootPath={path}/></section>;
  return <section className="ov-page" data-testid="project-home">
    <header className="ov-page-head"><div className="ov-head-main"><div className="ov-title-row"><h1 className="page-title">{tree?.branch??project.name}</h1>{state!=='ended'&&<span className={`chip st-${state}`}>{badgeText(state,zh)}</span>}</div><p className="page-sub"><span className="mono" title={displayPath(path)}>{displayPath(path)}</span>{!scopeBranch&&<> · {trees.length} {zh?'个工作树':trees.length===1?'worktree':'worktrees'}</>} · {sessions.length} {zh?'个会话':sessions.length===1?'session':'sessions'}</p></div>
      <div className="page-actions"><button className="btn btn-primary" disabled={tree?.missing} onClick={()=>onCreate(projectId,path)}><Icon name="plus"/>{zh?'新建终端':'New terminal'}</button><button className="btn" onClick={()=>setDialog('tree')}><Icon name="branch"/>{zh?'新建工作树':'New worktree'}</button><div className="project-tools"><button className="icon-btn" aria-expanded={menu} aria-label={zh?'项目操作':'Project actions'} onClick={()=>setMenu(!menu)}><Icon name="more"/></button>{menu&&<div className="menu project-tools-menu"><button className="menu-item" onClick={()=>setFileView('file')}><Icon name="file"/>{zh?'浏览文件':'Files'}</button><button className="menu-item" onClick={()=>setFileView('diff')}><Icon name="branch"/>{zh?'查看更改':'Changes'}</button><button className="menu-item" onClick={()=>{setMenu(false);setDialog('manage');}}><Icon name="branch"/>{zh?'管理工作树':'Manage worktrees'}</button><button className="menu-item danger" onClick={()=>void remove()}><Icon name="trash"/>{zh?'移除项目':'Remove project'}</button></div>}</div></div></header>
    {tree?.missing&&<div className="catalog-banner"><Icon name="info"/><span>{zh?'工作树目录缺失。历史仍可阅读，重新定位后才能继续。':'Worktree directory is missing. History remains readable; locate the directory before continuing.'}</span><button className="btn" onClick={()=>setDialog('manage')}>{zh?'重新定位':'Locate directory'}</button></div>}{issue&&<p className="surface-error" role="alert">{issue}</p>}
    <div className="ov-metrics" data-testid="home-metrics">
      <div className="ov-metric-group" role="group" aria-label={zh?'会话状态':'Session status'} data-testid="home-status">{metric(zh?'运行中':'Running',sessions.filter(s=>stateOf(s)==='running').length,'running')}{metric(zh?'待处理':'Pending',attention.length,'needs',onInbox)}{metric(zh?'停滞':'Stalled',sessions.filter(s=>stateOf(s)==='stalled').length,'stalled')}{metric(scopeBranch?(zh?'已关注':'Followed'):(zh?'工作树':'Worktrees'),scopeBranch?followed.length:trees.length)}{metric(zh?'会话':'Sessions',sessions.length)}</div>
      <div className="ov-metric-group ov-usage" role="group" aria-label={usageLabel}>{weekTokens===undefined
        ?<div className="ov-metric ov-usage-none"><span className="ov-metric-label">{usageLabel}</span><span className="ov-metric-note">{zh?'暂无用量记录':'No usage recorded yet'}</span></div>
        :<><div className="ov-metric"><span className="ov-metric-label">{zh?'今日 Token':'Tokens today'}</span><span className="ov-metric-value"><b className="tnum">{number(todayTokens??0)}</b>{knownCost(todayRows)&&<i>{knownCost(todayRows)}</i>}</span></div><div className="ov-metric ov-metric-wide"><span className="ov-metric-label">{zh?'近 7 日 Token':'Tokens, past 7 days'}</span><span className="ov-metric-value"><b className="tnum">{number(weekTokens)}</b><i>{knownCost(weekRows)??(zh?'费用未知':'Cost unknown')}</i><span className="ov-spark" title={zh?'近 7 日每日 Token':'Daily tokens, past 7 days'}><Spark values={usageSeries} fill/></span></span></div></>}
        <button type="button" className="ov-metric ov-metric-more" onClick={()=>setDialog('usage')} title={zh?'用量明细':'Usage details'}><span>{zh?'明细':'Details'}</span><Icon name="chevR"/></button></div>
    </div>
    <div className="ov-body"><div className="ov-main">
      {scopeBranch
        ?section('active',zh?'进行中的会话':'Active sessions',activeSessions.length,null,activeSessions.length?<div className="ov-list">{activeSessions.map(s=>sessionRow(s,`${providerName(s.provider)} · ${time(s.updatedAt)}`))}</div>:empty(zh?'没有进行中的会话。新建终端开始工作。':'No active sessions. Start a new terminal to begin.'))
        :section('active',zh?'进行中的工作树':'Active worktrees',activeTrees.length,null,activeTrees.length?<div className="ov-list">{activeTrees.map(t=>{const running=allProjectSessions.filter(s=>sameCanonicalScope(s.worktreePath??project.path,t.path)&&live(s));const st=t.missing?'stalled':priority(running),pending=running.filter(s=>stateOf(s)==='needs'||stateOf(s)==='failed').length;return <button type="button" className="ov-row ov-tree-row" data-testid="home-tree-row" key={t.id} onClick={()=>onScopeChange(t.path)}><Icon name="branch"/><span className="ov-row-main"><span className="ov-row-title">{t.branch??(zh?'项目目录':'Project directory')}</span><span className="ov-row-ctx">{displayPath(t.path)}{running[0]?` · ${time(running[0].updatedAt)}`:''}</span></span><span className={`chip st-${st}`}>{pending?`${pending} ${zh?'个待处理':'pending'}`:st==='running'?`${running.filter(s=>stateOf(s)==='running').length} ${zh?'个运行中':'running'}`:badgeText(st,zh)}</span><Icon name="chevR" className="ov-row-go"/></button>;})}</div>:empty(zh?'没有进行中的工作树。':'No active worktrees.'))}
      {section('recent',scopeBranch?(zh?'最近结束':'Recently ended'):(zh?'最近活动':'Recent activity'),undefined,activity.length>0&&<button className="btn btn-ghost ov-head-btn" onClick={()=>{setActivityPage(0);setDialog('activity');}}>{zh?'全部活动':'All activity'}</button>,recent.length?activityRows(recent.slice(0,5)):empty(scopeBranch?(zh?'还没有结束的会话。':'No ended sessions yet.'):(zh?'这个项目还没有活动记录。':'No project activity yet.')))}
    </div><div className="ov-side">
      {section('followed',zh?'已关注':'Followed',followed.length,<button className="btn btn-ghost ov-head-btn" onClick={()=>{setPicked(new Set());setFollowQuery('');setDialog('follow');}}><Icon name="plus"/>{zh?'添加':'Add'}</button>,followed.length?<div className="ov-list">{followed.map(s=>sessionRow(s,[providerName(s.provider),...(scopeBranch?[]:[treeFor(s)?.branch??(zh?'项目目录':'Project directory')]),time(s.updatedAt)].join(' · ')))}</div>:empty(zh?'关注的会话会显示在这里。可在会话菜单中关注。':'Sessions you follow appear here. Follow one from its menu.'))}
    </div></div>
    {dialog==='usage'&&<SurfaceDialog title={zh?'用量明细':'Usage details'} subtitle={project.name} icon="layers" size="wide" onClose={closed}><UsagePanel data={data} initialProjectId={projectId}/></SurfaceDialog>}{dialog==='follow'&&<SurfaceDialog title={zh?'添加关注':'Add followed sessions'} subtitle={zh?'选择要关注的终端，确认后生效。':'Select terminals to follow, then confirm.'} icon="star" onClose={closed} footer={<><span className="sheet-foot-meta">{picked.size} {zh?'项已选择':'selected'}</span><button className="btn" disabled={busy} onClick={closed}>{zh?'取消':'Cancel'}</button><button className="btn btn-primary" disabled={busy||!picked.size} onClick={()=>void follow()}>{zh?'确认':'Confirm'}</button></>}><div className="sheet-form"><div className="sheet-filters"><label className="sheet-search"><Icon name="search"/><input aria-label={zh?'搜索终端':'Search terminals'} value={followQuery} onChange={e=>setFollowQuery(e.target.value)} placeholder={zh?'搜索终端：名称或项目':'Search terminal or project'}/></label></div><div className="sheet-scroll">{data.sessions.filter(s=>!s.archived&&`${s.title} ${data.projects.find(p=>p.id===s.projectId)?.name}`.toLowerCase().includes(followQuery.toLowerCase())).map(s=><label className={`follow-manage-row sheet-card${s.followed?' is-followed':''}`} key={s.id}><input type="checkbox" disabled={s.followed||busy} checked={s.followed||picked.has(s.id)} onChange={e=>setPicked(current=>{const next=new Set(current);e.target.checked?next.add(s.id):next.delete(s.id);return next;})}/><span className="sheet-card-icon"><AgentIcon provider={s.provider}/></span><span className="sheet-card-main"><strong>{s.title}</strong><small>{data.projects.find(p=>p.id===s.projectId)?.name} · {badgeText(stateOf(s),zh)}</small></span>{s.followed&&<span className="sheet-card-tag"><Icon name="check"/>{zh?'已关注':'Following'}</span>}</label>)}</div></div></SurfaceDialog>}{dialog==='activity'&&<SurfaceDialog title={zh?'最近活动':'Recent activity'} subtitle={project.name} icon="clock" onClose={closed} footer={<><span className="sheet-foot-meta">{activity.length} {zh?'条记录':'records'}</span><button className="btn" disabled={activityPage===0} onClick={()=>setActivityPage(p=>p-1)}>{zh?'上一页':'Previous'}</button><button className="btn" disabled={(activityPage+1)*10>=activity.length} onClick={()=>setActivityPage(p=>p+1)}>{zh?'下一页':'Next'}</button></>}><div className="sheet-scroll project-activity">{activityRows(activity.slice(activityPage*10,activityPage*10+10))}</div></SurfaceDialog>}{dialog==='manage'&&<WorktreeManager project={project} initialWorktreeId={tree?.id} onClose={closed} onChanged={onChanged} onSelected={onScopeChange}/>} {dialog==='tree'&&<NewWorktree projectId={projectId} projectPath={project.path} onClose={closed} onCreated={value=>{setDialog(undefined);setTrees(list=>[...list,value]);onScopeChange(value.path);onChanged();}}/>}</section>;
}

function NewWorktree({projectId,projectPath,onClose,onCreated}:{projectId:string;projectPath:string;onClose:()=>void;onCreated:(tree:Worktree)=>void}){
  const {locale}=useTranslation(),zh=locale==='zh-CN';
  const [customPath,setCustomPath]=useState<string>(),[branch,setBranch]=useState(''),[branches,setBranches]=useState<string[]>([]),[busy,setBusy]=useState(false),[issue,setIssue]=useState<string>();
  const slug=(branch.trim().split('/').pop()||'my-change').replace(/[^\w.-]+/g,'-')||'my-change';
  const path=customPath??`${displayPath(projectPath)}-${slug}`;
  const existing=branches.includes(branch.trim());
  useEffect(()=>{let current=true;void request('worktree.branches',{projectId}).then(rows=>{if(current)setBranches(rows.map(r=>r.name));}).catch(error=>{if(current)setIssue(String(error));});return()=>{current=false;};},[projectId]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(busy||!branch.trim()||!path.trim())return;setBusy(true);setIssue(undefined);try{onCreated(await request('worktree.create',{projectId,path:path.trim(),branch:branch.trim(),createBranch:!existing,operationId:operationId()}));}catch(error){setIssue(String(error));}finally{setBusy(false);}};
  return <SurfaceDialog title={zh?'新建工作树':'New worktree'} subtitle={zh?'创建 Git 工作树，保留独立的工作目录。':'Create a Git worktree with its own working directory.'} variant="plain" onClose={()=>{if(!busy)onClose();}} footer={<><button className="btn" disabled={busy} onClick={onClose}>{zh?'取消':'Cancel'}</button><button type="submit" form="create-worktree" className="btn btn-primary" disabled={busy||!path.trim()||!branch.trim()}>{busy?(zh?'创建中…':'Creating…'):(zh?'创建工作树':'Create worktree')}</button></>}><form id="create-worktree" onSubmit={event=>void submit(event)}><div className="field"><label htmlFor="new-tree-branch">{zh?'分支名':'Branch name'}</label><input id="new-tree-branch" required maxLength={120} value={branch} onChange={e=>setBranch(e.target.value)} placeholder="feature/my-change" list="new-tree-branches"/><datalist id="new-tree-branches">{branches.map(name=><option key={name} value={name}/>)}</datalist></div><div className="field"><label htmlFor="new-tree-path">{zh?'工作树目录':'Worktree directory'} <small>{existing?(zh?'使用已有分支':'Use existing branch'):(zh?'创建新分支':'Create new branch')}</small></label><input id="new-tree-path" required value={path} onChange={e=>setCustomPath(e.target.value)}/></div><p className="note">{zh?'会建立空工作树；请再明确创建第一个会话。':'Creates an empty worktree. Create its first session separately.'}</p>{issue&&<p className="surface-error" role="alert">{issue}</p>}</form></SurfaceDialog>;
}
