/* ThreadTerm v3 settings drawer. All values below are local, simulated fixtures. */
(() => {
  "use strict";
  const boot = () => {
    const api = window.ThreadTermPrototype;
    if (!api || !api.extendMenu || !api.featureState || !api.registerActions) return false;
    const defaults = {
      appearance: { theme: "system", language: "zh-CN", customThemes: [{ id: "ocean", name: "Ocean glass", accent: "#5db9ff" }] },
      shortcuts: { selector: "Ctrl+Shift+Space", floating: "Ctrl+Shift+O" },
      notifications: { enabled: true, mention: true, completed: true, sound: false, preview: true },
      overlay: { lightweight: false, floatingEnabled: true, hotkey: "Ctrl+Shift+O" },
      supervisor: { enabled: false, defaultMode: "notify", range: 15, threshold: 3, launchCounters: { checks: 0, alerts: 0 } },
      compatibility: { aiCompletion: true },
      data: { location: "D:\\ThreadTerm data", cacheRebuild: false, platform: "windows", migration: { status: "idle", target: "E:\\ThreadTerm data", keepSource: true, progress: 0 } },
      mobile: { enabled: false, access: "readonly", pairCode: "TT-482-910", expiresAt: 0, devices: [{ id: "pixel", name: "Pixel 9 · Chrome", access: "readonly", state: "connected", tokenExpiresAt: 0 }], commandReceipt: "" },
      tools: { finder: "disconnected", git: "available" },
      importText: "", importPreview: null, section: "appearance", scene: "normal", toolRuns: [], toolReceipt: "", shortcutNotice: ""
    };
    const state = api.featureState("settings", defaults);
    const esc = api.esc || ((v) => String(v ?? "").replace(/[&<>\"]/g, (x) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[x])));
    const icon = api.icon || (() => "");
    const save = () => api.save?.();
    // The legacy root renderer replaces #app; this drawer lives in #layers and can
    // refresh itself without restarting the whole shell on each field edit.
    // Let the originating click/change finish before replacing its control.
    const render = () => { save(); setTimeout(draw, 40); };
    const label = (zh, en) => state.appearance.language === "en" ? en : zh;
    const drawer = () => document.querySelector(".settings-drawer");
    const resolvedTheme = () => state.appearance.theme === "system"
      ? (window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light")
      : state.appearance.theme === "custom" ? "dark" : state.appearance.theme;
    const setCoreTheme = () => {
      const theme = resolvedTheme();
      if (api.store?.theme !== theme) api.setTheme?.(theme);
      const custom = state.appearance.theme === "custom" ? state.appearance.customThemes[0] : null;
      const root = document.documentElement;
      root.classList.toggle("settings-custom-theme", Boolean(custom));
      if (custom) {
        root.style.setProperty("--accent-strong", custom.accent);
        root.style.setProperty("--accent-soft", `${custom.accent}26`);
      } else ["--accent-strong", "--accent-soft"].forEach((name) => root.style.removeProperty(name));
    };
    const toggle = (action, checked, text) => `<label class="setting-switch"><input type="checkbox" data-action="${action}" ${checked ? "checked" : ""}><span></span>${text}</label>`;
    const section = (id, title, body) => `<section class="settings-group ${state.section === id ? "active" : ""}" data-settings-section="${id}">${id === "appearance" ? body : `<h3>${title}</h3>${body}`}</section>`;
    const btn = (text, action, attrs = "") => `<button type="button" class="btn-subtle" data-action="${action}" ${attrs}>${text}</button>`;
    function body() {
      const a = state.appearance, n = state.notifications, o = state.overlay, s = state.supervisor, d = state.data, m = state.mobile;
      const themeOptions = ["system", "light", "dark"].map((v) => `<button type="button" class="theme-choice ${a.theme === v ? "selected" : ""}" data-action="settings-theme" data-theme="${v}" aria-pressed="${a.theme === v}">${v === "system" ? "◐" : v === "light" ? "☀" : "☾"}<span>${({system:label("跟随系统", "System"), light:label("浅色", "Light"), dark:label("深色", "Dark")})[v]}</span></button>`).join("");
      const custom = a.customThemes.map((t) => `<li class="theme-pack${a.theme === "custom" ? " is-on" : ""}"><button type="button" class="theme-pack-main" data-action="settings-theme" data-theme="custom"><i style="background:${esc(t.accent)}"></i><span>${esc(t.name)}</span></button>${btn(label("删除", "Delete"), "settings-theme-delete", `data-theme-id="${esc(t.id)}"`)}</li>`).join("") || `<li class="theme-pack is-empty">${label("尚无自定义主题", "No custom themes")}</li>`;
      const shortcutNames = { selector: label("命令面板", "Command palette"), floating: label("浮窗", "Floating window") };
      const shortcutRows = Object.entries(state.shortcuts).map(([k,v]) => `<label class="shortcut-row"><span>${shortcutNames[k] || esc(k)}</span><input data-action="settings-shortcut" data-shortcut="${k}" value="${esc(v)}"><em></em></label>`).join("");
      const inventory = [[label("会话索引", "Session index"),"248 MB","182"],[label("工作区草稿", "Workspace drafts"),"1.4 MB","24"],[label("主题和偏好", "Themes & preferences"),"64 KB","8"],[label("可重建缓存", "Rebuildable cache"),"312 MB","—"]].map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join("");
      const devices = m.devices.map(x=>{ const tokenActive=x.state!=="revoked" && x.tokenExpiresAt>Date.now(); return `<li><span>${esc(x.name)}<small>${x.access === "readonly" ? label("只读", "Read-only") : label("完全控制", "Full control")} · ${x.state}${tokenActive ? "" : ` · ${label("令牌已过期", "token expired")}`}</small></span>${btn(label("改名", "Rename"),"settings-device-rename",`data-device="${x.id}"`)} ${btn(label("续期令牌", "Renew token"),"settings-device-token-renew",`data-device="${x.id}"`)} ${btn(label("撤销", "Revoke"),"settings-device-revoke",`data-device="${x.id}"`)}</li>`; }).join("") || `<li>${label("没有已配对设备", "No paired devices")}</li>`;
      const nav = [["appearance", label("外观", "Appearance")], ["controls", label("快捷键", "Shortcuts")], ["data", label("数据", "Data")], ["mobile", label("移动", "Mobile")], ["tools", label("工具", "Tools")]];
      const pairingActive = m.enabled && m.expiresAt > Date.now();
      const expires = pairingActive ? new Date(m.expiresAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : label("已过期", "expired");
      return `<div class="settings-drawer" role="dialog" aria-modal="true" aria-label="${label("设置", "Settings")}"><div class="settings-panel"><header><div class="settings-brand"><span class="settings-brand-ico">${icon("gear")}</span><div><p>ThreadTerm</p><h2>${label("设置", "Settings")}</h2></div></div>${btn("×","settings-close", 'aria-label="Close settings"')}</header><div class="settings-layout"><nav>${nav.map(x=>`<button type="button" data-action="settings-section" data-section="${x[0]}" class="${state.section===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav><div class="settings-scroll">
        ${section("appearance", label("外观", "Appearance"), `<div class="settings-card"><div class="settings-card-row"><div><div class="settings-card-title">${label("外观模式", "Appearance mode")}</div><p>${label("主题在此演示窗口中即时预览。", "Themes preview in this demo window.")}</p></div><div class="theme-mode-switch">${themeOptions}</div></div></div><div class="settings-card"><div class="settings-card-row"><div><div class="settings-card-title">${label("主题包", "Theme packs")}</div><p>${label("导入 JSON 主题或导出当前自定义主题。", "Import a JSON theme or export the current custom themes.")}</p></div><div class="inline-actions">${btn(label("导入主题", "Import theme"),"settings-theme-import")} ${btn(label("导出主题", "Export theme"),"settings-theme-export")}</div></div><ul class="theme-list">${custom}</ul></div><div class="settings-card"><div class="settings-card-row"><div><div class="settings-card-title">${label("显示语言", "Display language")}</div><p>${label("仅切换此演示窗口的界面文案。", "Only switches copy in this demo window.")}</p></div><select class="settings-select" data-action="settings-language"><option value="zh" ${a.language!=="en"?"selected":""}>中文</option><option value="en" ${a.language==="en"?"selected":""}>English</option></select></div></div>`) }
        ${section("controls", label("快捷键与提醒", "Shortcuts & attention"), `<p>${label("录入组合键后会检查冲突；保存前不会替换已有快捷键。", "New combinations are checked for conflicts before replacing an existing shortcut.")}</p>${shortcutRows}<div class="setting-divider"></div>${toggle("settings-notifications",n.enabled,label("允许系统通知", "Allow system notifications"))}${toggle("settings-notification-mentions",n.mention,label("提及和需要批准", "Mentions and approvals"))}${toggle("settings-notification-completed",n.completed,label("任务完成", "Completed tasks"))}${toggle("settings-notification-sound",n.sound,label("播放提示音", "Play a sound"))}${btn(label("预览通知", "Preview notification"),"settings-notification-preview")} ${btn(label("发送测试", "Send test"),"settings-notification-test")}<div class="setting-divider"></div>${toggle("settings-lightweight",o.lightweight,label("轻量模式", "Lightweight mode"))}<p class="hint">${o.lightweight ? label("轻量模式已启用：独立浮窗和浮窗热键不可用。", "Lightweight mode is on: floating windows and their hotkey are unavailable.") : label("浮窗热键", "Floating window hotkey")} <kbd>${esc(o.hotkey)}</kbd></p><div class="setting-divider"></div>${toggle("settings-supervisor",s.enabled,label("默认启用监督", "Enable supervisor by default"))}<label>${label("观察范围（分钟）", "Observation range (minutes)")}<input type="range" min="5" max="60" step="5" value="${s.range}" data-action="settings-supervisor-range"><output>${s.range}</output></label><label>${label("连续停滞阈值", "Consecutive stall threshold")}<input type="number" min="1" max="8" value="${s.threshold}" data-action="settings-supervisor-threshold"></label><p class="hint">${label("监督会按默认规则检查范围内的连续停滞，这与单次“提醒我”不同。", "Supervisor evaluates repeated stalls in its range; it is distinct from a one-off reminder.")}</p>`) }
        ${section("data", label("数据、导入与迁移", "Data, import & migration"), `<p>${esc(d.location)} · ${label("此处均为合成数据。", "all data here is synthetic.")}</p><table class="settings-table"><thead><tr><th>${label("类别", "Category")}</th><th>${label("大小", "Size")}</th><th>${label("项目", "Items")}</th></tr></thead><tbody>${inventory}</tbody></table>${d.platform === "mac" ? `<p class="hint">${label("macOS 管理浏览器引擎缓存，不能在此安排重建。", "macOS manages browser-engine cache; rebuilding cannot be scheduled here.")}</p>` : toggle("settings-cache",d.cacheRebuild,label("下次启动时重建可重建缓存", "Rebuild cache next start"))}<div class="setting-divider"></div><p>${label("设置包只包含主题、通知、快捷键与浮层偏好；不包含会话、输出、密钥、配对设备或审计记录。", "The settings bundle includes themes, notifications, shortcuts and overlay preferences only; it excludes sessions, output, keys, paired devices and audit history.")}</p>${btn(label("下载设置 JSON", "Download settings JSON"),"settings-export")}<label>${label("粘贴设置 JSON 以导入", "Paste settings JSON to import")}<textarea data-action="settings-import-text" placeholder='{"app":"ThreadTerm", ...}'>${esc(state.importText)}</textarea></label>${btn(label("验证并查看差异", "Validate & preview differences"),"settings-import-preview")} ${state.importPreview ? `<div class="import-preview">${state.importPreview.message}<div>${state.importPreview.sections.map(x=>`<label><input type="checkbox" data-action="settings-import-select" data-import-section="${x.key}" ${x.selected ? "checked" : ""}>${esc(x.name)} · ${esc(x.status)}</label>`).join("")}</div>${btn(label("应用所选栏目", "Apply selected sections"),"settings-import-apply")} ${btn(label("取消", "Cancel"),"settings-import-cancel")}</div>` : ""}<div class="setting-divider"></div><label>${label("迁移目标", "Migration target")}<input data-action="settings-migration-target" value="${esc(d.migration.target)}"></label>${toggle("settings-migration-keep",d.migration.keepSource,label("迁移后保留源数据", "Retain source data after migration"))}<div class="inline-actions">${btn(label("运行预检", "Run precheck"),"settings-migration-precheck")} ${btn(label("开始迁移", "Start migration"),"settings-migration-start")} ${btn(label("取消", "Cancel"),"settings-migration-cancel")} ${btn(label("回滚", "Rollback"),"settings-migration-rollback")}</div><div class="migration-state"><progress value="${d.migration.progress}" max="100"></progress><span>${esc(d.migration.status)} ${d.migration.progress ? `${d.migration.progress}%` : ""}</span>${d.migration.status === "failed" ? btn(label("重试", "Retry"),"settings-migration-start") : ""}${d.migration.status.startsWith("completed") ? btn(label("立即重启演示", "Restart demo now"),"settings-migration-restart") : ""}${d.migration.status.startsWith("restart simulated") && d.migration.keepSource ? btn(label("清理已保留源", "Clean retained source"),"settings-migration-cleanup") : ""}</div>`) }
        ${section("mobile", label("桌面移动连接", "Desktop mobile access"), `${toggle("settings-mobile",m.enabled,label("启用移动访问", "Enable mobile access"))}<p class="pair-code">${m.enabled ? `${label("配对码", "Pair code")}: <strong>${m.pairCode}</strong> · ${label("expires at", "expires at")} ${expires} ${btn(label("续期", "Renew"),"settings-mobile-renew")} ${btn(label("立即使配对码过期", "Expire pair code"),"settings-mobile-expire")}` : label("启用后显示模拟 QR 码和短期配对码。", "Enable to show a mock QR code and expiring pairing code.")}</p>${m.enabled ? `<div class="mock-qr" aria-label="mock pairing QR">▦<br>▦▦</div><label>${label("新设备权限", "New device access")}<select data-action="settings-mobile-access"><option value="readonly" ${m.access==="readonly"?"selected":""}>${label("只读", "Read-only")}</option><option value="full" ${m.access==="full"?"selected":""}>${label("完全控制", "Full control")}</option></select></label>${btn(label("模拟连接设备", "Simulate device connection"),"settings-device-connect", pairingActive ? "" : "disabled")} ${btn(label("断开所有设备", "Disconnect all"),"settings-device-disconnect")} ${btn(label("重新连接", "Reconnect"),"settings-device-reconnect")}` : ""}<ul class="device-list">${devices}</ul>`) }
        ${section("tools", label("外部工具连接", "External tool connections"), `<p>${label("此面板展示能力矩阵，不启动进程也不访问网络。", "This panel demonstrates the capability matrix; it does not start processes or use a network.")}</p>${Object.entries(state.tools).map(([id,status])=>`<div class="tool-row"><span>${({vscode:"VS Code",finder:"Finder / Explorer",git:"Git client"})[id]}<small>${status}</small></span>${btn(status === "connected" ? label("断开", "Disconnect") : label("连接演示", "Connect demo"),"settings-tool",`data-tool="${id}"`)}</div>`).join("")}`) }
      </div></div></div></div>`;
    }
    function enhance() {
      const controls = document.querySelector('[data-settings-section="controls"]');
      if (controls && !controls.querySelector('.supervisor-launch-counts')) {
        const counts = state.supervisor.launchCounters || { checks: 0, alerts: 0 };
        controls.insertAdjacentHTML('beforeend', `<div class="supervisor-launch-counts"><div class="setting-divider"></div><p class="hint">${label("本次启动监督计数", "Supervisor counters for this launch")}: ${counts.checks} ${label("次检查", "checks")} · ${counts.alerts} ${label("个警示", "alerts")}。${label("它们不会作为历史审计保存。", "They are not retained as historical audit data.")}</p></div>`);
      }
      if (controls && !controls.querySelector('.compatibility-settings')) {
        controls.insertAdjacentHTML('beforeend', `<div class="compatibility-settings"><div class="setting-divider"></div><h4>${label("AI 补全兼容性", "AI completion compatibility")}</h4>${toggle("settings-ai-completion",state.compatibility.aiCompletion,label("启用补全兼容启发式", "Enable completion compatibility heuristic"))}<p class="hint">${label("此选项只控制模拟的 AI 补全兼容策略，不会启用监督、后台检查或审计。", "This only controls the simulated AI completion compatibility heuristic; it does not enable supervision, background checks, or audit.")}</p><div class="setting-divider"></div><p class="hint" data-notification-receipt>${esc(state.notifications.testReceipt || label("尚未发送通知测试。", "No notification test sent."))}</p></div>`);
      }
      const tools = document.querySelector('[data-settings-section="tools"]');
      if (tools && !tools.querySelector('.tool-lifecycle')) {
        const runs = state.toolRuns || [];
        tools.insertAdjacentHTML('beforeend', `<div class="tool-lifecycle"><div class="setting-divider"></div><h4>${label("Windows 工具接口演示", "Windows tool interface demo")}</h4><p>${label("只模拟窗口与进程状态；不会启动任何工具。", "Simulates window and process state only; no tool is launched.")}</p><label>${label("绝对工作目录", "Absolute working directory")}<input data-tool-cwd value="D:\\project\\orbit"></label><label>${label("打开位置", "Open target")}<select data-tool-target><option value="workspace">${label("工作区", "Workspace")}</option><option value="floating">${label("浮窗", "Floating window")}</option></select></label><label>${label("启动方式", "Launch mode")}<select data-tool-mode><option value="background">${label("后台", "Background")}</option><option value="focus">${label("前台并聚焦", "Foreground & focus")}</option></select></label>${btn(label("创建演示工具", "Create demo tool"),"settings-tool-create")}<ul class="tool-run-list">${runs.length ? runs.map(r=>`<li data-tool-run="${r.id}"><span><b>${esc(r.name)}</b><small>${esc(r.cwd)} · ${r.target} · ${r.mode} · ${r.state}</small></span>${btn(label("显示", "Show"),"settings-tool-show",`data-run="${r.id}"`)} ${btn(label("关闭", "Close"),"settings-tool-close",`data-run="${r.id}" data-close="graceful"`)} ${btn(label("强制", "Force"),"settings-tool-close",`data-run="${r.id}" data-close="force"`)}</li>`).join('') : `<li>${label("尚未创建演示工具。", "No demo tools created.")}</li>`}</ul></div>`);
      }
      const toolLifecycle = tools?.querySelector('.tool-lifecycle');
      if (toolLifecycle) {
        const target = toolLifecycle.querySelector('[data-tool-target]');
        if (target?.querySelector('option[value="floating"]')) {
          const option = target.querySelector('option[value="floating"]');
          option.value = 'separate-window';
          option.textContent = label("独立窗口", "Separate window");
        }
        if (!toolLifecycle.querySelector('[data-tool-receipt]')) toolLifecycle.insertAdjacentHTML('beforeend', `<p class="hint" data-tool-receipt>${esc(state.toolReceipt || label("尚无工具操作回执。", "No tool operation receipt yet."))}</p>`);
        if (state.data.platform !== 'windows') toolLifecycle.innerHTML = `<div class="setting-divider"></div><p class="hint">${label("外部工具演示仅在 Windows 合成场景中可用。", "External-tool demo is available only in the synthetic Windows scenario.")}</p>`;
      }
      const mobile = document.querySelector('[data-settings-section="mobile"]');
      if (mobile && !mobile.querySelector('.mobile-command-demo')) {
        const connected = state.mobile.enabled && state.mobile.devices.some(d => d.state === 'connected');
        const canControl = state.mobile.enabled && state.mobile.devices.some(d => d.access === 'full' && d.state === 'connected' && d.tokenExpiresAt > Date.now());
        mobile.insertAdjacentHTML('beforeend', `<div class="mobile-command-demo"><div class="setting-divider"></div><h4>${label("设备命令演示", "Device command demo")}</h4><p>${canControl ? label("已连接的完全控制设备可以发送演示命令。", "A connected full-control device can send demo commands.") : label("只读、撤销或令牌过期的设备只能查看状态；命令保持禁用。", "Read-only, revoked, or token-expired devices may view status only; commands remain disabled.")}</p><button class="btn-subtle" data-action="settings-device-command" ${canControl ? '' : 'disabled'}>${label("发送演示命令", "Send demo command")}</button>${state.mobile.commandReceipt ? `<p class="hint" data-command-receipt>${esc(state.mobile.commandReceipt)}</p>` : ''}${connected ? '' : `<p class="hint">${label("配对码已过期或移动访问未启用；重新连接后才可用。", "The pairing code expired or mobile access is off; reconnect before use.")}</p>`}</div>`);
      }
    }
    let lastInvoker = null;
    const focusable = () => [...drawer()?.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])') || []];
    function draw() {
      const old = drawer();
      const active = document.activeElement;
      const selector = active?.dataset?.action ? `[data-action="${active.dataset.action}"]${active.dataset.shortcut ? `[data-shortcut="${active.dataset.shortcut}"]` : ""}` : null;
      const start = typeof active?.selectionStart === "number" ? active.selectionStart : null;
      if (old) { old.outerHTML = body(); setTimeout(() => { enhance(); const next = selector && drawer()?.querySelector(selector); if (next) { next.focus(); if (start !== null && typeof next.setSelectionRange === "function") next.setSelectionRange(start, start); } }, 0); }
    }
    function open(el) { lastInvoker = el instanceof HTMLElement ? el : document.activeElement; setCoreTheme(); const layer = document.querySelector("#layers") || document.body; if (!drawer()) { layer.insertAdjacentHTML("beforeend", body()); enhance(); setTimeout(() => focusable()[0]?.focus(), 0); } }
    function close() { drawer()?.remove(); if (lastInvoker?.isConnected) lastInvoker.focus(); }
    // Core dialogs have their own overlay; CSS hides this drawer while one is open.
    // Do not retain a class here, because Escape may close the core dialog directly.
    const lowerDrawerForDialog = () => {};
    const restoreDrawerAfterDialog = () => drawer()?.classList.remove("settings-dialog-open");
    function toast(message) { api.toast?.(message); }
    function exportBundle() { return { app:"ThreadTerm", kind:"threadterm-settings-bundle", schemaVersion:1, exportedAt:new Date().toISOString(), sections:{ theme:{ theme:state.appearance.theme, language:state.appearance.language, customThemes:state.appearance.customThemes.map(({ id, name, accent }) => ({ id, name, accent })) }, notifications:{ enabled:state.notifications.enabled, mention:state.notifications.mention, completed:state.notifications.completed, sound:state.notifications.sound, preview:state.notifications.preview }, overlay:{ lightweight:state.overlay.lightweight, floatingEnabled:state.overlay.floatingEnabled, hotkey:state.overlay.hotkey }, shortcuts:{ selector:state.shortcuts.selector, floating:state.shortcuts.floating } } }; }
    function download(name, text) { const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0); }
    const isRecord = (value) => value && typeof value === "object" && !Array.isArray(value);
    const validShortcut = (value) => typeof value === "string" && /^(?:Ctrl|Cmd|Meta)(?:\+(?:Ctrl|Cmd|Meta|Alt|Shift))*\+(?:[A-Z]|Space|F(?:[1-9]|1[0-2]))$/i.test(value.trim());
    const cleanTheme = (value) => { if (!isRecord(value) || !["system", "light", "dark", "custom"].includes(value.theme)) return null; const language = value.language === "en" || value.language === "zh-CN" ? value.language : state.appearance.language; const themes = Array.isArray(value.customThemes) ? value.customThemes.filter((item) => isRecord(item) && typeof item.id === "string" && typeof item.name === "string" && /^#[0-9a-f]{6}$/i.test(item.accent)).slice(0, 8).map(({ id, name, accent }) => ({ id:id.slice(0, 40), name:name.slice(0, 60), accent })) : state.appearance.customThemes; return { theme:value.theme, language, customThemes:themes }; };
    const cleanSection = (key, value) => { if (!isRecord(value)) return null; if (key === "theme") return cleanTheme(value); if (key === "notifications") return ["enabled","mention","completed","sound","preview"].every((name) => typeof value[name] === "boolean") ? Object.fromEntries(["enabled","mention","completed","sound","preview"].map((name) => [name, value[name]])) : null; if (key === "overlay") return typeof value.lightweight === "boolean" && typeof value.floatingEnabled === "boolean" && validShortcut(value.hotkey) ? { lightweight:value.lightweight, floatingEnabled:value.floatingEnabled, hotkey:value.hotkey.trim() } : null; if (key === "shortcuts") return validShortcut(value.selector) && validShortcut(value.floating) ? { selector:value.selector.trim(), floating:value.floating.trim() } : null; return null; };
    function previewImport() { let b; try { b=JSON.parse(state.importText); } catch { state.importPreview={message:label("JSON 无效，未更改任何设置。", "Invalid JSON; no settings were changed."),sections:[]}; return render(); } if(!isRecord(b) || b.app!=="ThreadTerm"||b.kind!=="threadterm-settings-bundle"||b.schemaVersion!==1 || !isRecord(b.sections)){state.importPreview={message:label("不是受支持的 ThreadTerm 设置包。", "This is not a supported ThreadTerm settings bundle."),sections:[]};return render();} const allowed=["theme","notifications","overlay","shortcuts"]; const sections=allowed.map((key) => ({ key, value:cleanSection(key, b.sections[key]) })).filter((x) => x.value).map((x) => ({ key:x.key, name:x.key, value:x.value, status:JSON.stringify(x.key === "theme" ? state.appearance : state[x.key]) !== JSON.stringify(x.value) ? "changed" : "unchanged", selected:true })); state.importPreview={message:sections.length ? label("选择要应用的栏目。未知、敏感或格式错误的字段已忽略。", "Choose sections to apply. Unknown, sensitive, or invalid fields were ignored.") : label("没有可安全导入的设置。", "No safely importable settings were found."),sections};render(); }
    let migrationGeneration = 0;
    const migrationTimers = new Set();
    const clearMigrationTimers = () => { migrationGeneration++; migrationTimers.forEach(clearTimeout); migrationTimers.clear(); };
    const migrationLater = (callback) => { const generation=migrationGeneration; const timer=setTimeout(() => { migrationTimers.delete(timer); if (generation===migrationGeneration) callback(); }, 350); migrationTimers.add(timer); };
    function migration(status, progress=0) { state.data.migration.status=status;state.data.migration.progress=progress; render(); }
    api.onReset?.(clearMigrationTimers);
    api.extendMenu("settings", () => `<div class="menu-separator"></div><button type="button" class="menu-item" data-action="settings-open">${icon("gear")} ${label("设置", "Settings")}</button>`);
    api.extendMenu("scenario", () => `<button type="button" class="menu-item" data-action="settings-scene" data-scene="permission">${icon("shield")} ${label("设置：权限受限", "Settings: permission denied")}</button><button type="button" class="menu-item" data-action="settings-scene" data-scene="migration-fail">${icon("info")} ${label("设置：迁移失败", "Settings: migration failed")}</button><button type="button" class="menu-item" data-action="settings-scene" data-scene="pair-expired">${icon("clock")} ${label("设置：配对码过期", "Settings: pair code expired")}</button><button type="button" class="menu-item" data-action="settings-scene" data-scene="token-expired">${icon("clock")} ${label("设置：设备令牌过期", "Settings: device token expired")}</button>`);
    api.registerActions({
      "settings-open": open, "settings-close": close,
      "settings-section": (el)=>{state.section=el.dataset.section;render();},
      "settings-theme": (el)=>{state.appearance.theme=el.dataset.theme;setCoreTheme();render();},
      "settings-language": (el)=>{state.appearance.language=el.value === "zh" ? "zh-CN" : el.value;document.documentElement.lang=state.appearance.language;save();api.render?.();draw();},
      "settings-theme-import": (el)=>{lowerDrawerForDialog();api.openDialog?.(label("导入主题", "Import theme"), label("粘贴一个合成主题对象以供验证。", "Paste one synthetic theme object for validation."), `<label>JSON<textarea data-theme-import-json placeholder='{"id":"violet","name":"Violet","accent":"#9b7bff"}'></textarea></label>`, btn(label("验证并导入", "Validate & import"), "settings-theme-import-confirm"), { invoker:el });},
      "settings-theme-import-confirm": ()=>{let theme;try{theme=JSON.parse(document.querySelector('[data-theme-import-json]')?.value || "");}catch{setTimeout(lowerDrawerForDialog,0);return toast(label("主题 JSON 无效。", "Theme JSON is invalid."));}if(!isRecord(theme)||typeof theme.id!=="string"||typeof theme.name!=="string"||!/^#[0-9a-f]{6}$/i.test(theme.accent)||theme.id.length>40||theme.name.length>60){setTimeout(lowerDrawerForDialog,0);return toast(label("主题必须包含有效的 id、名称和六位颜色。", "Theme needs a valid id, name, and six-digit color."));}state.appearance.customThemes=state.appearance.customThemes.filter((item)=>item.id!==theme.id);state.appearance.customThemes.push({id:theme.id,name:theme.name,accent:theme.accent});api.closeDialog?.();restoreDrawerAfterDialog();render();toast(label("演示主题已验证并导入。", "Demo theme validated and imported."));},
      "settings-theme-export": ()=>download("threadterm-theme.json",JSON.stringify(state.appearance.customThemes,null,2)),
      "settings-theme-delete": (el)=>{state.appearance.customThemes=state.appearance.customThemes.filter(x=>x.id!==el.dataset.themeId);render();},
      "settings-shortcut": (el)=>{const key=el.dataset.shortcut,value=el.value.trim(), reserved=["ctrl+k","ctrl+alt+n","ctrl+s"];const conflict=Object.entries(state.shortcuts).find(([id,v])=>id!==key&&v.toLowerCase()===value.toLowerCase());if(!validShortcut(value)||reserved.includes(normalizeShortcut(value))||conflict){toast(!validShortcut(value)||reserved.includes(normalizeShortcut(value))?label("请输入可用的组合键；核心快捷键已保留。", "Enter a supported shortcut; core shortcuts are reserved."):label(`与 ${conflict[1]} 冲突，未保存。`,`Conflicts with ${conflict[1]}; not saved.`));draw();return;}state.shortcuts[key]=value;state.overlay.hotkey=state.shortcuts.floating;render();},
      "settings-notifications": (el)=>{state.notifications.enabled=el.checked;render();}, "settings-notification-mentions": (el)=>{state.notifications.mention=el.checked;render();}, "settings-notification-completed": (el)=>{state.notifications.completed=el.checked;render();}, "settings-notification-sound": (el)=>{state.notifications.sound=el.checked;render();}, "settings-ai-completion": (el)=>{state.compatibility.aiCompletion=el.checked;render();},
      "settings-notification-preview": ()=>toast(label("预览：orbit 的 Codex 会话需要你的批准。", "Preview: Codex in orbit needs your approval.")), "settings-notification-test": ()=>{state.notifications.testReceipt=state.notifications.enabled?label("通知测试已送达合成通知中心。", "Notification test delivered to the synthetic notification center."):label("通知已关闭：测试仅生成本地合成回执。", "Notifications are off: the test produced only a local synthetic receipt.");render();toast(state.notifications.testReceipt);},
      "settings-lightweight": (el)=>{state.overlay.lightweight=el.checked;state.overlay.floatingEnabled=!el.checked;render();}, "settings-supervisor": (el)=>{state.supervisor.enabled=el.checked;state.supervisor.launchCounters ||= { checks: 0, alerts: 0 };if(el.checked)state.supervisor.launchCounters.checks++;render();}, "settings-supervisor-range": (el)=>{state.supervisor.range=Number(el.value);render();}, "settings-supervisor-threshold": (el)=>{state.supervisor.threshold=Math.min(8,Math.max(1,Number(el.value)||1));render();},
      "settings-cache": (el)=>{state.data.cacheRebuild=el.checked;render();}, "settings-export": ()=>download("threadterm-settings-demo.json",JSON.stringify(exportBundle(),null,2)), "settings-import-text": (el)=>{state.importText=el.value;save();}, "settings-import-preview": previewImport,
      "settings-import-select": (el)=>{const x=state.importPreview?.sections.find(x=>x.key===el.dataset.importSection);if(x)x.selected=el.checked;save();}, "settings-import-cancel": ()=>{state.importPreview=null;render();},
      "settings-import-apply": ()=>{const p=state.importPreview;if(!p)return;for(const x of p.sections.filter(x=>x.selected)){if(x.key==="theme")state.appearance={ ...state.appearance, ...x.value };else state[x.key]={ ...state[x.key], ...x.value };}state.importPreview=null;setCoreTheme();render();toast(label("已应用所选设置。", "Selected settings applied."));},
      "settings-migration-target": (el)=>{state.data.migration.target=el.value;state.data.migration.precheckedTarget="";save();}, "settings-migration-keep": (el)=>{state.data.migration.keepSource=el.checked;render();}, "settings-migration-precheck": ()=>{const target=state.data.migration.target.trim(), source=state.data.location;const normalized=(value)=>value.replace(/[\\/]+$/, "").toLowerCase(); const absolute=/^[A-Za-z]:\\/.test(target); let reason="";if(!absolute)reason=label("迁移目标必须是 Windows 绝对路径。", "Migration target must be an absolute Windows path.");else if(normalized(target)===normalized(source))reason=label("迁移目标不能与当前数据位置相同。", "Migration target cannot be the current data location.");else if(normalized(target).startsWith(normalized(source)+"\\"))reason=label("迁移目标不能位于当前数据目录内。", "Migration target cannot be inside the current data directory.");else if(target.toLowerCase().includes("denied"))reason=label("目标位置没有权限。", "Target location has no permission.");if(reason){state.data.migration.precheckedTarget="";migration("precheck failed",0);return toast(reason);}state.data.migration.precheckedTarget=target;migration("precheck passed",0);},
      "settings-migration-start": ()=>{const m=state.data.migration;if(m.precheckedTarget!==m.target.trim() || m.status!=="precheck passed")return toast(label("开始迁移前请为当前目标运行预检。", "Run precheck for the current target before starting migration."));clearMigrationTimers();m.sourceLocation=state.data.location;m.sourceCleaned=false;m.activated=false;migration("copying",10);const tick=()=>{if(state.data.migration.status!=="copying")return;const next=state.data.migration.progress+30;if(next>=100)migration("completed · restart required",100);else{state.data.migration.progress=next;render();migrationLater(tick);}};migrationLater(tick);}, "settings-migration-cancel": ()=>{clearMigrationTimers();migration("cancelled; source retained",0);}, "settings-migration-rollback": ()=>{const m=state.data.migration;clearMigrationTimers();if(m.sourceCleaned)return toast(label("源数据已清理，不能回滚演示迁移。", "Source data was cleaned; this demo migration cannot roll back."));if(m.activated&&!m.keepSource)return toast(label("未保留源数据的已激活迁移不能回滚。", "An activated migration without retained source data cannot roll back."));if(m.activated&&m.sourceLocation)state.data.location=m.sourceLocation;m.activated=false;migration("rolled back; source retained",0);}, "settings-migration-cleanup": ()=>{const m=state.data.migration;if(!m.keepSource || !m.status.startsWith("restart simulated"))return toast(label("只有已激活且保留源数据的迁移可以清理源数据。", "Only activated migrations that retained source data can clean it."));lowerDrawerForDialog();api.openDialog?.(label("清理已保留源", "Clean retained source"), label("此演示会标记合成源数据为已清理。", "This demo marks the synthetic source data as cleaned."), `<p>${label("确认后无法通过迁移回滚恢复该演示源数据。", "After confirmation this demo source cannot be restored by migration rollback.")}</p>`, btn(label("确认清理", "Confirm cleanup"), "settings-migration-cleanup-confirm"), {});}, "settings-migration-cleanup-confirm": ()=>{const m=state.data.migration;m.sourceCleaned=true;api.closeDialog?.();restoreDrawerAfterDialog();migration("source cleanup complete",100);}, "settings-migration-restart": ()=>{const m=state.data.migration;if(!m.status.startsWith("completed"))return;state.data.location=m.target;m.activated=true;clearMigrationTimers();migration("restart simulated; migration active",100);},
      "settings-mobile": (el)=>{state.mobile.enabled=el.checked;if(el.checked && state.mobile.expiresAt <= Date.now())state.mobile.expiresAt=Date.now()+5*60*1000;if(el.checked)state.mobile.devices.forEach((device)=>{if(!device.tokenExpiresAt)device.tokenExpiresAt=Date.now()+24*60*60*1000;});render();}, "settings-mobile-renew": ()=>{state.mobile.expiresAt=Date.now()+5*60*1000;render();toast(label("配对码已续期五分钟。", "Pairing code renewed for five minutes."));}, "settings-mobile-expire": ()=>{state.mobile.expiresAt=Date.now()-1;render();}, "settings-mobile-access": (el)=>{state.mobile.access=el.value;render();}, "settings-device-connect": ()=>{if(!state.mobile.enabled || state.mobile.expiresAt<=Date.now())return toast(label("配对码已过期，请先续期。", "Pairing code expired; renew it first."));state.mobile.devices.push({id:"ipad-"+Date.now(),name:"iPad Air · Safari",access:state.mobile.access,state:"connected",tokenExpiresAt:Date.now()+24*60*60*1000});render();}, "settings-device-disconnect": ()=>{state.mobile.devices.forEach(x=>x.state="disconnected");render();}, "settings-device-reconnect": ()=>{state.mobile.devices.forEach(x=>{if(x.state!=="revoked"&&x.tokenExpiresAt>Date.now())x.state="connected";});render();}, "settings-device-rename": (el)=>{const x=state.mobile.devices.find(x=>x.id===el.dataset.device);if(!x)return;lowerDrawerForDialog();api.openDialog?.(label("重命名设备", "Rename device"), label("仅更改此合成设备的显示名称。", "Changes only this synthetic device's display name."), `<label>${label("设备名称", "Device name")}<input data-device-name value="${esc(x.name)}"></label>`, btn(label("保存", "Save"), "settings-device-rename-save", `data-device="${esc(x.id)}"`), { invoker:el });}, "settings-device-rename-save": (el)=>{const x=state.mobile.devices.find(x=>x.id===el.dataset.device), value=document.querySelector("[data-device-name]")?.value.trim();if(!x || !value)return toast(label("请输入设备名称。", "Enter a device name."));x.name=value.slice(0,80);api.closeDialog?.();restoreDrawerAfterDialog();render();}, "settings-device-token-renew": (el)=>{const x=state.mobile.devices.find(x=>x.id===el.dataset.device);if(!x||x.state==="revoked")return toast(label("已撤销的设备不能续期令牌。", "A revoked device cannot renew its token."));x.tokenExpiresAt=Date.now()+24*60*60*1000;render();}, "settings-device-revoke": (el)=>{const x=state.mobile.devices.find(x=>x.id===el.dataset.device);if(x){x.state="revoked";x.tokenExpiresAt=0;}render();},
      "settings-tool-create": ()=>{const cwd=document.querySelector('[data-tool-cwd]')?.value.trim()||'', validRoots=["d:\\project\\orbit","d:\\threadterm data","e:\\threadterm data"];if(state.data.platform!=="windows")return toast(label("此演示仅限 Windows。", "This demo is Windows-only."));if(!/^[A-Za-z]:\\/.test(cwd)||!validRoots.includes(cwd.toLowerCase())){state.toolReceipt=label("未创建：目录必须是已知的 Windows 合成绝对目录。", "Not created: directory must be a known synthetic Windows absolute directory.");render();return toast(state.toolReceipt);}const target=document.querySelector('[data-tool-target]')?.value||"workspace",mode=document.querySelector('[data-tool-mode]')?.value||"background",run={id:"tool-"+Date.now(),name:"ThreadTerm tool host",cwd,target,mode,state:mode==="focus"?"shown and focused":"running in background"};state.toolRuns.push(run);state.toolReceipt=label(`已创建 ${target} · ${run.state} 的合成工具。`, `Synthetic tool created for ${target} · ${run.state}.`);render();toast(state.toolReceipt);},
      "settings-tool-show": (el)=>{const run=state.toolRuns.find(x=>x.id===el.dataset.run);if(!run)return;run.state="shown and focused";state.toolReceipt=label(`已显示 ${run.name}。`, `${run.name} shown.`);render();toast(state.toolReceipt);},
      "settings-tool-close": (el)=>{const run=state.toolRuns.find(x=>x.id===el.dataset.run);if(!run)return;run.state=el.dataset.close==="force"?"force closed":"closed gracefully";state.toolReceipt=el.dataset.close==="force"?label("演示工具已强制关闭。","Demo tool force closed."):label("演示工具已正常关闭。","Demo tool closed gracefully.");render();toast(state.toolReceipt);},
      "settings-device-command": ()=>{const device=state.mobile.devices.find((item)=>item.state==="connected"&&item.access==="full"&&item.tokenExpiresAt>Date.now());if(!state.mobile.enabled||!device){state.mobile.commandReceipt=label("命令未发送：需要未撤销的完全控制设备和有效令牌。", "Command not sent: an unrevoked full-control device and valid token are required.");render();return;}state.mobile.commandReceipt=label(`已收到 ${device.name} 的合成命令回执。`, `Synthetic command receipt received from ${device.name}.`);render();},
      "settings-tool": (el)=>{const id=el.dataset.tool;state.tools[id]=state.tools[id]==="connected"?"disconnected":"connected";render();}, "settings-scene": (el)=>{if(el.dataset.scene==="permission")state.data.migration.status="permission denied";if(el.dataset.scene==="migration-fail")state.data.migration.status="failed";if(el.dataset.scene==="pair-expired"){state.mobile.enabled=true;state.mobile.expiresAt=Date.now()-1;}if(el.dataset.scene==="token-expired"){state.mobile.enabled=true;state.mobile.expiresAt=Date.now()+5*60*1000;state.mobile.devices.forEach((device)=>device.tokenExpiresAt=0);}open();draw();}
    });
    document.addEventListener("change", (event) => {
      const el = event.target.closest?.('[data-action]');
      if (!el) return;
      if (el.dataset.action === 'settings-mobile-access') { state.mobile.access = el.value; render(); }
      if (el.dataset.action === 'settings-language') { state.appearance.language = el.value === 'zh' ? 'zh-CN' : el.value; document.documentElement.lang = state.appearance.language; save(); api.render?.(); draw(); }
      if (el.dataset.action === 'settings-shortcut') {
        const key = el.dataset.shortcut, value = el.value.trim(), reserved = ["ctrl+k", "ctrl+alt+n", "ctrl+s"];
        const conflict = Object.entries(state.shortcuts).find(([id, v]) => id !== key && v.toLowerCase() === value.toLowerCase());
        if (!validShortcut(value) || reserved.includes(normalizeShortcut(value)) || conflict) { toast(!validShortcut(value) || reserved.includes(normalizeShortcut(value)) ? label("请输入可用的组合键；核心快捷键已保留。", "Enter a supported shortcut; core shortcuts are reserved.") : label(`与 ${conflict[1]} 冲突，未保存。`, `Conflicts with ${conflict[1]}; not saved.`)); draw(); }
        else { state.shortcuts[key] = value; state.overlay.hotkey = state.shortcuts.floating; render(); }
      }
    });
    document.addEventListener("input", (event) => {
      const el = event.target.closest?.('[data-action]');
      if (!el) return;
      if (el.dataset.action === 'settings-import-text') { state.importText = el.value; save(); }
      if (el.dataset.action === 'settings-migration-target') { state.data.migration.target = el.value; state.data.migration.precheckedTarget = ""; save(); }
    });
    document.addEventListener("click", (event) => { if (event.target.closest?.('[data-action="close-dialog"]')) setTimeout(restoreDrawerAfterDialog, 0); });
    const normalizeShortcut = (value) => String(value).replace(/\s+/g, "").toLowerCase().replace("meta", "cmd");
    const shortcutForEvent = (event) => {
      const modifiers = [];
      if (event.ctrlKey) modifiers.push("ctrl"); if (event.metaKey) modifiers.push("cmd"); if (event.altKey) modifiers.push("alt"); if (event.shiftKey) modifiers.push("shift");
      const key = event.code === "Space" ? "space" : event.key.length === 1 ? event.key.toLowerCase() : event.key.toLowerCase();
      return [...modifiers, key].join("+");
    };
    document.addEventListener("keydown", (event) => {
      if (event.isComposing) return;
      const activeDrawer = drawer();
      if (activeDrawer && event.key === "Escape" && !document.querySelector(".dialog")) { event.preventDefault(); close(); return; }
      if (activeDrawer && event.key === "Tab") { const items=focusable(); if (!items.length) return; const index=items.indexOf(document.activeElement); if (event.shiftKey && index<=0) { event.preventDefault(); items.at(-1).focus(); } else if (!event.shiftKey && index===items.length-1) { event.preventDefault(); items[0].focus(); } return; }
      if (!event.ctrlKey && !event.metaKey) return;
      const value = shortcutForEvent(event);
      if (normalizeShortcut(value) === normalizeShortcut(state.shortcuts.selector)) {
        event.preventDefault();
        api.baseActions?.["open-palette"]?.(document.activeElement instanceof HTMLElement ? document.activeElement : document.body);
      } else if (normalizeShortcut(value) === normalizeShortcut(state.shortcuts.floating) && !state.overlay.lightweight) {
        event.preventDefault();
        const item = api.sessions?.().find((session) => !api.isUnavailable?.(session));
        if (!item) return toast(label("没有可用于浮窗的会话。", "No session is available for a floating window."));
        const trigger=document.createElement("button"); trigger.dataset.session=item.id;
        api.baseActions?.["float-open"]?.(trigger);
      }
    });
    window.matchMedia?.("(prefers-color-scheme: dark)").addEventListener?.("change", () => { if (state.appearance.theme === "system") setCoreTheme(); });
    setCoreTheme();
    return true;
  };
  if (!boot()) { let tries=0; const t=setInterval(()=>{if(boot()||++tries>80)clearInterval(t);},50); }
})();
